[project]
name = "danmaku-compress"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dmconvert>=0.0.4",
    "python-dotenv>=0.9.9",
    "fastapi>=0.115.12",
    "uvicorn[standard]>=0.29.0",
    "schedule>=1.2.2",
]
